### ISSUE TITLE
Submitting UNREACHABLE passive result for host sets it as DOWN if the host has no parents

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nagioscore#289]
Submitting UNREACHABLE passive result for host sets it as DOWN if the host has no parents

base/checks.c line 2894:

	/* host has no parents, so it is DOWN */
	if(hst->parent_hosts == NULL) {
		log_debug_info(DEBUGL_CHECKS, 2, "Host has no parents, so it is DOWN.\n");
		return HOST_DOWN;
	}

Should be:

	/* host has no parents, so it is DOWN */
	if(hst->parent_hosts == NULL && hst->current_state != HOST_UNREACHABLE) {
		log_debug_info(DEBUGL_CHECKS, 2, "Host has no parents, so it is DOWN.\n");
		return HOST_DOWN;
	}

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/a195a231740bc4d25e5f849fbcc7b10f6f9efbd7

**Comment by gahujipo** [comment]
The commit a195a23 broke the "Translate Passive Host Checks Option". This means, that after this commit, even when translate_passive_host_checks is set to 1, hosts remain unreachable, even hosts that should be down based on their hierarchy remain unreachable. 

In my opinion the changes in the mentioned commit didn't fix what this issue was originally about.
