### ISSUE TITLE
xdata/xodtemplate.c bug in option-deprecation code

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#345]
In xdata/xodtemplate.c, in these two places in the code:

```
       2400                         else if(!strcmp(variable, "retry_interval") || !strcmp(variable, "retry_check_interval")) {
       2401                                 if(!strcmp(variable, "normal_retry_interval"))
       2402                                         logit(NSLOG_CONFIG_WARNING, TRUE, "WARNING: The normal_retry_interval attribute is deprecated and will be removed in future versions. Please use retry_interval instead.\n");

       2859                         else if(!strcmp(variable, "retry_interval") || !strcmp(variable, "retry_check_interval")) {
       2860                                 if(!strcmp(variable, "normal_retry_interval"))
       2861                                         logit(NSLOG_CONFIG_WARNING, TRUE, "WARNING: The normal_retry_interval attribute is deprecated and will be removed in future versions. Please use retry_interval instead.\n");
```

Notice that the initial conditional is testing for "retry_check_interval"
but the nested conditional is testing for "normal_retry_interval" instead,
which can never be matched at that point because of the first conditional.
There is clearly a mismatch of expectations here. I'm not sure exactly
what option names were intended, so I can't tell which lines of code
need correction.

Originally from https://support.nagios.com/forum/viewtopic.php?t=42888&start=9999#bottom

**Comment by jfrickson** [comment]
Looking into it.

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/ffddc292c07776a365a01ebf9b7bd5411f9840da

**Comment by ovidiustanila** [comment]
The message should be updated to. It now says:
WARNING: The normal_retry_interval attribute is deprecated and will be removed in future versions. Please use retry_interval instead.

should be:
WARNING: The retry_check_interval attribute is deprecated and will be removed in future versions. Please use retry_interval instead.

**Comment by knweiss** [comment]
@frickson Both in `ffddc29` and `774d864` you only fixed the `strcmp()` string but not the `logit()` string in the line beneath the `strcmp()`. I.e. the code is correct but the deprecation warnings are still wrong in nagios-4.3.2.
