### ISSUE TITLE
Core 4.3.1 - Still <defunct> processes on Solaris 11.3 64-bit (i86pc)

### ISSUE THREAD

**Issue by Semirben** [NagiosEnterprises/nagioscore#387]
Hi everyone,

I really hoped commit 02e5ed499e302d523ab3d16f110d2a74340c63de would fix this issue but somehow it's still present. My Nagios installation got a lot "<defunct>" processes which are child processes of the core workers. The strange thing is that I neither see a high CPU usage (~0,1 - 2 %) nor a high memory usage (~700MB in total).

Here are a few information regarding my system and my compilation of Nagios:

```
-bash-4.1$ uname -mrsv
SunOS 5.11 11.3 i86pc
CFLAGS="-m64" ./configure --prefix=/opt/nagios --with-nagios-user=nagios --with-nagios-group=nagios --with-command-user=nagios --with-command-group=nagios --sysconfdir=/opt/etc/nagios --with-gd-inc=/usr/include/gd2 --with-httpd-conf=/opt/etc/apache/conf.d
```

And the proof that my nagios executable is 64-bit on a i386 architecture (Output from Solaris 11 IPS packaging system):
```
file 10e0e0f6a2f081fd762fa9e3aa8e12b07cec2d9d chash=3b90e12297077575cadf34ec3a5838a90c71d9d0 elfarch=i386 elfbits=64 elfhash=0fa9ad79a1f8b930f50b65dcb73d01fe07d716c3 group=nagios mode=0774 owner=nagios path=opt/nagios/bin/nagios pkg.csize=261987 pkg.size=834400
```

Output of `ps -ef | grep nagios | grep defunct | wc -l`:
`90`

`tail -f nagios.log`:
```
[1498742840] wproc: Core Worker 14810: job 134 (pid=5247) timed out. Killing it
[1498742840] wproc: Core Worker 14810: job 134 with pid 5247 reaped at timeout. timeouts=125; started=136
[1498742841] wproc: Core Worker 14806: job 130 (pid=3083) timed out. Killing it
[1498742841] wproc: Core Worker 14806: job 130 with pid 3083 reaped at timeout. timeouts=128; started=136
[...]
```

I got 	65 hosts and 267 active service checks, so nothing really special. The only change I did to my nagios configuration is to increase the *service_check_timeout* to 150 seconds due to some SMTP checks which take some time
`service_check_timeout=150`

Hopefully somebody can help me with this issue. It's nothing really serious but quite annoying when the nagios logfile is flooded with these timeout messages and the process list displays a lot of defunctional nagios processes.

**Comment by hedenface** [comment]
I'm just now stepping into this maintainer role, and I don't (yet) have an environment where I can test, replicate, and/or issue a fix.

I will get to it as soon as I can, I just wanted to communicate that to you so that you're aware of the situation. :)

That said: if anyone out there can help at all by either verifying replicating or fixing, it would be much appreciated!

**Comment by Semirben** [comment]
Hi Bryan,

no problem if it takes some time. It's nothing really serious as Nagios is running without any impact of this issue.

If it's necessary I can provide my build script and sanitized config files.

Regards,
Daniel

**Comment by hedenface** [comment]
Are you able to reproduce this with the current master branch? (4.4.0)

I believe this issue was fixed from code in other issues.

**Comment by Semirben** [comment]
I compiled the current master branch and I'm able to reproduce the issue
```
[14:59:57 - dheitepriem@cs-monitor-brem-p:~] ps -ef | grep defunct
  nagios 16397 15626   0        - ?           0:00 <defunct>
  nagios 16407 15627   0        - ?           0:00 <defunct>
  nagios 16529 15634   0        - ?           0:00 <defunct>
  nagios 16741 15636   0        - ?           0:00 <defunct>
  nagios 16528 15633   0        - ?           0:00 <defunct>
[15:00:07 - dheitepriem@cs-monitor-brem-p:~] ps -ef | grep 15634
  nagios 15634 15621   0 14:54:35 ?           0:00 /opt/nagios/bin/nagios --worker /opt/nagios/var/rw/nagios.qh
  nagios 16529 15634   0        - ?           0:00 <defunct>
[15:00:33 - dheitepriem@cs-monitor-brem-p:~] ps -ef | grep 15621
[...]
  nagios 15621  6994   0 14:54:35 ?           0:00 /opt/nagios/bin/nagios -d /opt/etc/nagios/nagios.cfg
[...]
```
Nothing suspicious in the logfile itself:
```
[1528894475] Nagios 4.4.0 starting... (PID=15621)
[1528894475] Local time is Wed Jun 13 14:54:35 CEST 2018
[1528894475] LOG VERSION: 2.0
[1528894475] qh: Socket '/opt/nagios/var/rw/nagios.qh' successfully initialized
[1528894475] qh: core query handler registered
[1528894475] qh: echo service query handler registered
[1528894475] qh: help for the query handler registered
[1528894475] wproc: Successfully registered manager as @wproc with query handler
[1528894475] wproc: Registry request: name=Core Worker 15622;pid=15622
[1528894475] wproc: Registry request: name=Core Worker 15623;pid=15623
[1528894475] wproc: Registry request: name=Core Worker 15624;pid=15624
[1528894475] wproc: Registry request: name=Core Worker 15625;pid=15625
[1528894475] wproc: Registry request: name=Core Worker 15626;pid=15626
[1528894475] wproc: Registry request: name=Core Worker 15628;pid=15628
[1528894475] wproc: Registry request: name=Core Worker 15627;pid=15627
[1528894475] wproc: Registry request: name=Core Worker 15629;pid=15629
[1528894475] wproc: Registry request: name=Core Worker 15631;pid=15631
[1528894475] wproc: Registry request: name=Core Worker 15630;pid=15630
[1528894475] wproc: Registry request: name=Core Worker 15632;pid=15632
[1528894475] wproc: Registry request: name=Core Worker 15633;pid=15633
[1528894475] wproc: Registry request: name=Core Worker 15634;pid=15634
[1528894475] wproc: Registry request: name=Core Worker 15635;pid=15635
[1528894475] wproc: Registry request: name=Core Worker 15636;pid=15636
[1528894475] wproc: Registry request: name=Core Worker 15638;pid=15638
[1528894475] wproc: Registry request: name=Core Worker 15637;pid=15637
[1528894475] wproc: Registry request: name=Core Worker 15639;pid=15639
[1528894475] wproc: Registry request: name=Core Worker 15640;pid=15640
[1528894475] wproc: Registry request: name=Core Worker 15641;pid=15641
[1528894475] wproc: Registry request: name=Core Worker 15642;pid=15642
[1528894475] wproc: Registry request: name=Core Worker 15645;pid=15645
[1528894475] wproc: Registry request: name=Core Worker 15644;pid=15644
[1528894475] wproc: Registry request: name=Core Worker 15643;pid=15643
[1528894475] Successfully launched command file worker with pid 15646
```

**Comment by stevenwilliamson** [comment]
Hi,

I am seeing this problem on SmartOS (which is a descendant of Solaris) and i believe i have found the root cause.

The processes that the nagios core worker processes launch are never reaped after they have exited resulting in the zombie processes.

The root cause is the worker process never handles any SIGCHD signals and so never increments the reapable count which is ultimately responsible for triggering the code path where processes are reaped.

Then signal handler here https://github.com/NagiosEnterprises/nagioscore/blob/fa88e1c5c42438e6238b838bf80aa3c8d71c433d/lib/worker.c#L511-L514 is not been triggered.

I have confirmed this with a short dtrace script to confirm that the worker process is not handling the sigchld signals. Script below for reference

```
#!/usr/sbin/dtrace -s

proc:::signal-handle
/ curpsinfo->pr_zoneid == 28 && execname == "nagios" /
{
  printf("pid %d execname %s signal %d sig_handler_at 0x%p", pid, execname, args[0], args[2]);
}
```

Going a step further to confirm, the worker process also never calls waitpid which was checked with the below

```
#!/usr/sbin/dtrace -s

pid$target::waitpid:entry
{
  printf("pid %d execname %s", pid, execname);
}
```

If we look at the section of code responsible for wiring up signal handling there are two options either we use sigaction or signal. https://github.com/NagiosEnterprises/nagioscore/blob/fa88e1c5c42438e6238b838bf80aa3c8d71c433d/lib/worker.c#L55-L65


Checking my packaged version on SmartOS is using the signal() variant as can be seen in this disassembly

```
enter_worker:                   pushq  %rbp
enter_worker+1:                 movq   %rsp,%rbp
enter_worker+4:                 pushq  %r13
enter_worker+6:                 pushq  %r12
enter_worker+8:                 pushq  %rbx
enter_worker+9:                 movq   %rsi,%rbx
enter_worker+0xc:               subq   $0xb8,%rsp
enter_worker+0x13:              movl   %edi,+0x3d753(%rip)      <nagios`master_sd>
enter_worker+0x19:              movq   +0x3f090(%rip),%rax      <nagios`__stack_chk_guard>
enter_worker+0x20:              movq   %rax,-0x28(%rbp)
enter_worker+0x24:              xorl   %eax,%eax
enter_worker+0x26:              call   -0x60d8b <PLT=libc.so.1`getppid>
enter_worker+0x2b:              movl   $0x49190a,%edi
enter_worker+0x30:              movl   %eax,+0x3d732(%rip)      <nagios`parent_pid>
enter_worker+0x36:              call   -0x612bb <PLT=libc.so.1`chdir>
enter_worker+0x3b:              movl   $0x496913,%edi
enter_worker+0x40:              call   -0x612c5 <PLT=libc.so.1`chdir>
enter_worker+0x45:              movl   $0x1000,%edi
enter_worker+0x4a:              call   -0x1ecf  <fanout_create>
enter_worker+0x4f:              xorl   %esi,%esi
enter_worker+0x51:              xorl   %edi,%edi
enter_worker+0x53:              movq   %rax,+0x3d706(%rip)      <nagios`ptab>
enter_worker+0x5a:              call   -0x612ef <PLT=libc.so.1`setpgid>
enter_worker+0x5f:              movl   $0x4851c0,%esi   <sigchld_handler>
enter_worker+0x64:              movl   $0x12,%edi
enter_worker+0x69:              call   -0x60dfe <PLT=libc.so.1`signal>
enter_worker+0x6e:              movl   $0x4c3fc0,%edi   <nagios`_iob+0x80>
enter_worker+0x73:              call   -0x61248 <PLT=libc.so.1`fileno>
```

I think the root cause is in the difference between signal() on Linux vs Solaris. On Solaris at least if we check the man page it states that before calling the signal handler and delivering the signal it returns the signal handler back to the default state. For subsequent signals to be recivied on Solaris the signal() call has to be made again to re-set the signal handler.

```
The disp argument specifies the signal's disposition,
       which may be SIG_DFL, SIG_IGN, or the address of a signal handler. If
       signal() is used, disp is the address of a signal handler, and sig is
       not  SIGILL, SIGTRAP, or SIGPWR, the system first sets the signal's
       disposition to  SIG_DFL before executing the signal handler.
```

So the fix is to call signal and set up the handler again after seeing one signal, or alternatively the better approach would be to change the build to use sigaction on Solaris and decedents as sigaction is available there.

**Comment by stevenwilliamson** [comment]
Just realised the links in my last comment to the code sections are from the wrong branch :) but the issue still stands just ignore the links :)

**Comment by stevenwilliamson** [comment]
OK yup it looks like were missing an include somewhere include/config.h is never actually included when building lib/worker.c.

Iv'e tested this by just running the C preprocessor and getting it to output the headers it includes

```
/opt/tools/gcc49/bin/gcc -E -MM -H worker.c 2>headers
```

Then grepping for any mention of config and ignoring system headers

```
--<root@pkg-2016q4>-(/data/chroot/dev-2016Q4-x86_64)-</home/pbulk/build/net/nagios-base/work/nagios-4.3.2/lib>--
-> grep config headers | grep -v usr
```

Yields nothing
