### ISSUE TITLE
Nagios process memory leak(s)

### ISSUE THREAD

**Issue by marce1000** [NagiosEnterprises/nagioscore#455]
Nagios 4.3.4 on Red Hat Enterprise Linux Server release 6.4 ; the nagios daemon grows in (virtual) memory size ; after 3 or 4 weeks it exits with a SIGHUP.
M.

**Comment by hedenface** [comment]
What broker modules do you have loaded? Can I see your `nagios.cfg` please? Any log file details you can share - preferably close to the SIGHUP?

**Comment by marce1000** [comment]
[nagios-crash.txt](https://github.com/NagiosEnterprises/nagioscore/files/1521468/nagios-crash.txt)

[nagios-cfg.txt](https://github.com/NagiosEnterprises/nagioscore/files/1521466/nagios-cfg.txt)

No special broker modules used; actually the process terminates with SIGTERM (not SIGHUP) 
, after about 4 to 6 weeks.
Initial memory size is only about 66Meg but after the mentioned period it grows beyond 8Gig , eventually  experiencing a SIGTERM (is this the OS?). Note that there is no operator intervention prior to the 'SIGTERM crash'. I will attach an excerpt from nagios.log just before and after the crash; (look for the string SIGTERM). nagios.cfg is also included.

**Comment by hedenface** [comment]
It looks like a clean shutdown at least. Also, that is quite a bit of workers - what are the specs of the beast running this thing?

We'll put this on the burner for the time being, because obviously replicating is going to take a server a bit of time to do it. I will say that I've had a few reports of the memory leak, so I'm looking into that actively and would like to say the fix will be in 4.4.0.

**Comment by marce1000** [comment]
>look like a clean shutdown
Indeed but as stated it is not done by us, I can only assume that in the end the nagios
process gets so big that it is killed by the Linux-OS.

>A bit of workers
Did not change the default, but we make extensive use of check_wmi_plus for checking windows
servers and services, CPU,disk, etc... ; guess nagios decided to increase the number of workers

>specs of the server
Nagios is running on an HP proliant dl360p gen8 with 32Gig of memory and 24 CPU's.

>fix in 4.4.0 
OK, thanks

Current workaround : I have a cronjob running every hour which checks if NAGIOS is running, if not
then de NAGIOS service is started again.

Marc.

**Comment by hedenface** [comment]
It would be pretty helpful for investigation if you could supply me with a sanitized complete configuration. Also, are you able to turn debug logging on to -1 and then turn the verbosity up to 2 and supply that debug log? If there is any sensitive data you don't want the world to see, your best bet would be to send it to me via PM on the forums: bheden @ https://support.nagios.com/forum/

**Comment by hedenface** [comment]
Also, @marce1000 Are you able to perhaps install the 4.4.0 branch and see if your issues are resolved?

**Comment by hkraal** [comment]
I'm seeing high memory usage on two different installations running Nagios 4.3.4 as well. I tend to restart the processes before the usages gets to high so I don't experience the SIGHUP @marce1000 has seen.

- #1 (personal) is running CentOS 7 with 28 hosts and 80 services
- #2 (corporate) is running Debian 7 with 607 hosts and 2820 services

Both are pretty clean & standard Nagios instances but both do use NRPE for a lot of checks. On my personal instance the memory usage was ~700 MB before I restarted after which it consumed a mere 15 MB memory:
```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
23994 nagios    20   0  733068 717444   1064 S  0.0 39.1  57:14.04 nagios
```

I could install 4.4 on my personal instance but as it grows really slow (200 MB in 30 days or so) it might not be very useful.
Let me know if I could do anything to help, I'm lingering in the #nagios irc channel (same username) if you want to quickly ask something.

**Comment by box293** [comment]
In GitHub select the branch drop down and you will see `nagios-4.4.0-alpha1`
https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.4.0-alpha1

You can download it using this command:
```
git clone --recursive https://github.com/NagiosEnterprises/nagioscore.git --branch nagios-4.4.0-alpha1
```

Then the build should be the same as per this KB article:
https://support.nagios.com/kb/article.php?id=96

**Comment by hkraal** [comment]
I've been running nagios-4.4.0-alpha1 (166dd3a) along the 4.3.4 since Friday but both show a growth in memory usage over the last ~60 hours:

Friday January 5th @ 21:26 +0100
```
4.3.4: 1800 KB
4.4.0-a1: 1724 KB
```

Friday January 8th @ 11:18 +0100
```
4.3.4: 24412 KB
4.4.0-a1: 28072 KB
```


I've just found out there is a 1 MB default limit on the debug logs (shouldn't hurt to increase a bit imho) which I cranked up and restarted both instances.

For obvious reasons I won't upload my 4.3.4 debug log publicly but I'm willing to share it with the devs working on this issue; let me know where to send them.

**Comment by hedenface** [comment]
Send it in to devteam@nagios.com please.

**Comment by marce1000** [comment]
As far as I am concerned my boss won't allow an alpha release on the production environment, and since I have no test environment , I will report back once the official 4.4.0 is out w.r.t the status of this issue.
M.

**Comment by hedenface** [comment]
Received, @hkraal . Will investigate and get back to you shortly.

**Comment by hedenface** [comment]
@hkraal I haven't seen anything that stands out. Also, I have a 4.4.0 Core up and running, and am not seeing any memory leaks at all. I have the process memory graphed on a 1 min interval, and there is nothing to indicate such a problem.

Are you able to send in your Nagios configuration files? At the very least `nagios.cfg`, but the entire config directory (gzipped of course) could potentially be helpful.

**Comment by box293** [comment]
So there have been some changes recently in relation to how the lock file is created and where it is created (for security reasons).

I was doing some testing on upgrading an older set of configs that were placed onto a fresh build of Core 4.3.4. I simply renamed the `etc` directory that was created as part of the build process and copied my existing configs into a new `etc` directory.

Nagios started OK, but when I tried to stop the service or get the status I noticed that is threw some errors and the nagios binary was still running.

The problem was in the existing `nagios.cfg` the following was set:
```
lock_file=/usr/local/nagios/var/nagios.lock
```
The init script that comes with 4.3.4 is a lot more secure, and the setting in `nagios.cfg` that was created as part of the build process is:
```
lock_file=/var/run/nagios.lock
```

I updated my `nagios.cfg` to use `/var/run/nagios.lock`. I killed the existing Nagios processes, after this the nagios service would start / stop correctly.

What I am unsure about is if when you upgraded to 4.3.4 did you install the latest version of the init script as part of the build process.

What I suggest to do moving forward is as follows:
1) Replace the init script with the 4.3.4 version if not already done so (https://support.nagios.com/kb/article.php?id=96)
2) Update your `nagios.cfg` with `lock_file=/var/run/nagios.lock`

Once these steps have been performed can you please report back if your memory issue still continues or not.

**Comment by box293** [comment]
@marce1000 what version of Nagios Core were you previously running where this problem did not occur?

**Comment by box293** [comment]
@hkraal do you have service dependencies defined on your test system. If you do, are you able to remove them and see if the memory growth stops?

**Comment by hkraal** [comment]
@box293 I've updated my systemd config and adjusted the lock file yesterday; no difference to memory usage.

I've 19 service dependencies defined in my config. I've remove them from my 4.4.0 instance and will  report back in ~24h with the results.

**Comment by VMike1** [comment]
Yesterday updated Nagios 4.1.1 to 4.3.4 and got the same behaviour: about +1Gb memory to nagios process per 12 hours.
Platform is the same: Red Hat Enterprise Linux Server release 6.6.

I have no any service dependencies defined.

On the test system without many checks, I still can't reproduce the problem.

**Comment by hkraal** [comment]
@VMike1 what about host dependencies?

I've host and (had) service dependencies defined. The Nagios instance of my employer does have host but no service dependencies. This seems to rule out service dependencies as the culprit but host dependencies could still be in the running?

**Comment by VMike1** [comment]
My Nagios config doesn't contain any hostdependency or servicedependency definitions. All of hosts definitions are without 'parent' option.

**Comment by VMike1** [comment]
@hkraal Do you have enable_environment_macros set to 1 in nagios.cfg?
My config had such setting. After changing it to 0, process memory isn't growing such fast. I need to collect more statistics after reconfiguration, however.

**Comment by hkraal** [comment]
@VMike1 only on my 4.3.4 (nagios-prd) instance but both my instances grow in memory usage.
```
# grep enable_environment_macros nagios-*/etc/nagios.cfg
nagios-dev/etc/nagios.cfg:enable_environment_macros=0
nagios-prd/etc/nagios.cfg:enable_environment_macros=1
```

**Comment by box293** [comment]
Thanks for checking the service dependencies, after some more testing on my systems I can confirm that service dependencies are not related to the issue. At least we have rule out one more thing. 

I also ruled out the plugins themselves by changing all the check commands to check_dummy and I can still reproduce the issue.

**Comment by hedenface** [comment]
I did some testing yesterday, and I think the commit here https://github.com/NagiosEnterprises/nagioscore/commit/ad9d527ef488a748344509b2232bd95b49ab6f9e is the culprit. I fixed it in https://github.com/NagiosEnterprises/nagioscore/commit/b9eacdc08b41646425f333a03a514e42d7cdfe6d. I'd like those of you who can to compile the 4.4 branch and see if this fixes your issues, please.

**Comment by hedenface** [comment]
Wasn't actually fixed in https://github.com/NagiosEnterprises/nagioscore/commit/b9eacdc08b41646425f333a03a514e42d7cdfe6d but I think it may have been in the very next one (https://github.com/NagiosEnterprises/nagioscore/commit/f3d63ee4f6d7a8382ff94859ff4ab79c25fe9eeb)

**Comment by hkraal** [comment]
@hedenface I've updated to f3d63ee but I'm missing the regular workers in my process list:
```
[root@vps08 nagios-dev]# ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
nagios   32527  0.0  0.1  13480  2112 ?        Ss   19:26   0:00 /usr/local/nagios-dev/bin/nagios -d /usr/local/nagios-dev/etc/nagios.cfg
nagios   32528  0.0  0.0  12564   668 ?        S    19:26   0:00  \_ /usr/local/nagios-dev/bin/nagios -d /usr/local/nagios-dev/etc/nagios.cfg
```

All checks are unable to run as well;
nagios.log:
```
[1515868440] Unable to run check for service 'NRPE' on host 'A'
[1515868441] Unable to run check for service 'SSL' on host 'B'
[1515868448] Unable to run check for service 'HTTPS' on host 'C'
[1515868450] Unable to run check for service 'SWAP' on host 'D'
[1515868456] Unable to run check for service 'disk D' on host 'E'
```

If you need the full debug logs let me know but I think this is the most informative part:
```
[1515868236.803746] [001.0] [pid=32527] clear_volatile_macros_r()
[1515868236.803748] [016.1] [pid=32527] Unable to run scheduled service check at this time
[1515868236.803751] [001.0] [pid=32527] get_next_valid_time()
```

**Comment by hedenface** [comment]
I was seeing this in mine as well. All was resolved when I made a `check_workers=` line in the main `nagios.cfg`. Not sure what happened with the automatic detection - I changed a few things, and am sure I caused it. But doing that should fix your issue.

**Comment by hedenface** [comment]
@hkraal I used that commit as well, and the weird thing is this: I used the 4.3.1 branch to make that revert and let it run over night. When I saw the graph this morning, I was very excited - as it fixed the issue. When I applied those same changes to the 4.4.0 branch, I am still seeing the memory leak. I think a problem has been resolved, but there appears to be another one lingering.

**Comment by hkraal** [comment]
@hedenface `check_workers=` indeed solves the missing worker part. I've restarted my instances and will let you know my findings as soon as I can. Keep up the awesome work there! 👍

**Comment by hkraal** [comment]
@hedenface it seems you're right and something else is lingering as well then. In 13 hours I'm seeing the following memory usages;

- 4.2.4: 1792 -> 1712 KB
- 4.3.4: 1668 -> 6392 KB
- 4.4.0a1@f3d63ee: 1672 -> 7200 KB

**Comment by hedenface** [comment]
@hkraal Please update to this commit and report your findings: https://github.com/NagiosEnterprises/nagioscore/commit/b5af4c8ce3b0b00088177754711f8adeb4a6a643

@box293 has found what we believe to be the source of the leak. The service/host info url (brand new as of 4.4.0) macros were not being cleared.

**Comment by hkraal** [comment]
@hedenface updated to 6391501 and restarted nagios, will report back when I've some insights.

**Comment by hedenface** [comment]
@hkraal waaaiiiitttt! The fix is the next one: https://github.com/NagiosEnterprises/nagioscore/commit/b5af4c8ce3b0b00088177754711f8adeb4a6a643

**Comment by hkraal** [comment]
@hedenface it is okay, 6391501 is the merge commit after b5af4c8 so I've got the fix

- 6391501 Merge branch 'nagios-4.4.0-alpha1' of github.com:NagiosEnterprises/nagioscore into nagios-4.4.0-alpha1
- b5af4c8 Pretty sure @box293 figured out the issue was related to the newly introduced host/service info macros (#316). This should solve the issue presented in #455
- 47f8897 fix for `check_workers=` after introducing bug in commit: bdd7b3

**Comment by hedenface** [comment]
Okay - I have this set up on a Nagios XI instance and I've just been recompiling and have the Nagios memory graphed - it looks like this doesn't actually fix it :( I think we may be on the right track, as @box293  had the problem disappear entirely when he reverted the commit.

**Comment by hkraal** [comment]
It's a good fix indeed but a 4.4.0a1 only one as far as I can tell as that's the only version to include the macro url feature unless it has been backported into 4.3.x?

Sofar my 4.4.0a1 build is using half of the memory which 4.3.4 does so I'm carefully optimistic. At least the fix prevents problems down the road so that's good ;)

**Comment by box293** [comment]
I can confirm that we have identified the source of the memory leak for 4.3.3 and 4.3.4.

Add the two lines `my_free(mac->x[MACRO_SERVICEINFOURL]);` and `my_free(mac->x[MACRO_HOSTINFOURL]);` to `common/macros.c` as per https://github.com/NagiosEnterprises/nagioscore/commit/b5af4c8ce3b0b00088177754711f8adeb4a6a643.

Then:
```
service nagios stop
./configure
make all 
make install
service nagios start
```

Memory leak should no longer be present in 4.3.3 and 4.3.4.

There are other memory leaks in the 4.4 alpha branch we are also tracking down.

**Comment by hkraal** [comment]
I've applied b5af4c8 to the 4.3.4 release source and recompiled Nagios. I will report back in a bit with my patched 4.3.4 experience

**Comment by VMike1** [comment]
I've also applied those two lines 'my_free' to the our installation (Nagios 4.3.4) and can confirm the memory leak is fixed.

**Comment by hkraal** [comment]
The big memory leak in 4.3.4 is indeed solved when applying b5af4c8 to it but there is still lingering a smaller leak compared to 4.2.4:

* 4.2.4: 1936 KB
* 4.3.4 with b5af4c8 patch: 4156 KB
* 4.4.0a1@6391501: 13016 KB

**Comment by box293** [comment]
@hkraal we are working on finding that additional leak in the 4.4.01a base

**Comment by marce1000** [comment]
Currently running 4.3.4 with the 'my_free patch' too : things look very promising indeed ; will keep monitoring nagios process memory size. M.

**Comment by hkraal** [comment]
Can confirm twice that b5af4c8 fixes the 4.3.4 leaks. Applied the patch to my employers production Nagios instance yesterday as well which stays stable at ~7 MB instead of 1,5 GB it was before the restart.

**Comment by hedenface** [comment]
@hkraal https://github.com/NagiosEnterprises/nagioscore/commit/0217319ba0011efb0a3fd3837461cb61dba535b4 is the commit that fixes this for the memory leak in 4.4.0. I've tested it on a few system, and it appears to work (especially since the fix was rather obvious once I compared the old code to the code I changed) - but I'd like an additional set of eyes if possible.

I'm closing this issue, and will get the rest of the 4.4.0 issues taken care of and we should have a 4.4.0 release early next week.

Thanks everyone!

**Comment by hkraal** [comment]
@hedenface I've recompiled an hour after your post and restarted my instances. There still seems to be a minor leak in 0217319; after ~36 hours I'm seeing the following numbers:

* 4.2.4: 1844 KB
* 4.3.4 with b5af4c8 patch: 1764 KB
* 4.4.0a1@0217319: 9036 KB

Moved forward to f8e12ab just now btw

**Comment by hkraal** [comment]
@hedenface I think the problem is in the notification part when it exits with return value 2. From my 4.4.0a1 nagios.log:
```
[1516618613] SERVICE NOTIFICATION: contact;website-url;URL;WARNING;notify-service-by-email;HTTP WARNING: HTTP/1.1 401 Unauthorized - 406 bytes in 0.039 second response time
[1516618613] wproc: NOTIFY job 11863 from worker Core Worker 18040 is a non-check helper but exited with return code 2
[1516618613] wproc:   host=website-url; service=URL; contact=contact
[1516618613] wproc:   early_timeout=0; exited_ok=1; wait_status=512; error_code=0;
[1516618613] wproc:   stderr line 01: Send options without primary recipient specified.
[1516618613] wproc:   stderr line 02: Usage: mail -eiIUdEFntBDNHRVv~ -T FILE -u USER -h hops -r address -s SUBJECT -a FILE -q FILE -f FILE -A ACCOUNT -b USERS -c USERS -S OPTION users
```

My 4.4.0 instance went from 1756 to 5924 KB in the last 24h so there is still a leak which i'm triggering but you aren't as far as I can tell.

**Comment by hedenface** [comment]
Yes but none of the commits you cited I believe have the fix. And of course, I jumped the gun and got everything all moved around out-of-sorts by pushing to master.

I think if you sync with the latest master now (https://github.com/NagiosEnterprises/nagioscore/commit/d28448bce75f392f2f312f40a7fcef0ab76dfaee) you'll notice that the memory leak goes away.

**Comment by hedenface** [comment]
That said, if that **doesn't** remove the memory leak, then I would very much like to investigate.

**Comment by hkraal** [comment]
Ah, that explains. I've moved to the master branch and I'm on d28448b as well now. If I see any signs of leaking I'll let you know but somehow I doubt that will happen. Thanks!

**Comment by hedenface** [comment]
@hkraal Any updates?

**Comment by hkraal** [comment]
@hedenface 1688 -> 2520 KB in the last 4 hours

**Comment by hedenface** [comment]
How often did you check it? Just once at startup, then 4 hours later? Or periodically through the time period? There is a slight ramp up period, where it has to continuously allocate memory for things until it's ready for example.

**Comment by hkraal** [comment]
@hedenface my config normally stabilizes at 1750 - 1850 KB memory usage. I checked at start and than after a couple of hours, current state:

T+0h: 1688
T+4h: 2520 
T+8h: 3148 

I've sent you my debug log, hopefully you see something there.

**Comment by hkraal** [comment]
After 24+ hours: T+29h: 6596 KB

**Comment by hedenface** [comment]
Reviewing the debug log now, thank you for sending it.

**Comment by hedenface** [comment]
@hkraal Can you update your configuration file to remove the offending following lines at least:

```
Warning: use_embedded_perl_implicitly is deprecated and will be removed.
Warning: enable_embedded_perl is deprecated and will be removed.
Warning: p1_file is deprecated and will be removed.
Warning: sleep_time is deprecated and will be removed.
Warning: external_command_buffer_slots is deprecated and will be removed. All commands are always processed upon arrival
Warning: command_check_interval is deprecated and will be removed. Commands are always handled on arrival
```

More data coming soon :)

**Comment by hedenface** [comment]
As an FYI, @hkraal it looks like I can confirm the memory leak using ***YOUR*** configurations you sent over. This is good news! Hopefully I can determine where the leak is with that. What operating system are you running on, btw?

**Comment by hkraal** [comment]
@hedenface that's good news! I will fix my config tomorrow. I'm running CentOS 7.4 x86_64.

**Comment by hedenface** [comment]
After I've disabled the service dependencies, it appears to have stabilized on my cent7 box at around 6868kB. It's been running for 3 hours now.

While you're fixing your configuration, please see if disabling servicedependencies fixes the leak for you as well. I'll be trying to track it down independently of that, but having additional confirmation is always grand.

**Comment by amgokak** [comment]
@box293 , @hedenface  We have installed Nagios 4.3.4 using RPM Package from CentOS 7.4  yum repository, And observing below graphs for Nagios process resource usage. Can you please suggest how to apply the patch suggested(b5af4c8.) in case of RPM based installation ?

![image](https://user-images.githubusercontent.com/14012736/37198060-f611751e-23a2-11e8-8d88-ca6961be121e.png)

Thanks.

**Comment by box293** [comment]
I've not had to do that before, but I assume if you build from source and do a `make install` with the patch included then you should have an updated copy. In the future when the next version of Nagios is made available via yum it will be OK.

**Comment by amgokak** [comment]
Thanks for the response
 
> I've not had to do that before
Does it mean this issue is addressed in nagios-4.3.4-5.el7.x86_64.rpm ? Currently we are using nagios-4.3.4-3.el7.x86_64.rpm.

Thanks.
