### ISSUE TITLE
Specific browser ONLY: Error: Could not read object configuration data! 

### ISSUE THREAD

**Issue by wiardvanrij** [NagiosEnterprises/nagioscore#505]
I have a issue when going trough the interface of nagios. I personally receive the following message:

![image](https://user-images.githubusercontent.com/5786097/39406371-181156bc-4bb6-11e8-8f98-cd7c533a12ca.png)

The "funny" part here is that my colleagues do not get this error. If I switch browser from Chrome to for instance Firefox: I also do not have this error anymore. 

I have tried the following already: 

- Checked all permisions for Nagios and Apache
- Restarted services, even rebooted the server
- Nagios configtest -v resulted in everything ok, no issues

- Flushed my browser cache
- Deleted local browser storage
- Deleted cookies
- Actually reinstalled Chrome

My issue affects the following sections in Nagios:

- Current Status
- System

I can actually access the tabs in "Reports".

Further information: 

- There are no errors / messages in my chrome Console on accessing the page
- I see no errors in apache log or nagios log
- Nagios Core 4.3.4
- Server version: Apache/2.4.29 (Ubuntu)
- Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Chrome Version 66.0.3359.117  (Official Build) (64-bit)
- Updated Chrome further to Version 66.0.3359.139 (Official Build) (64-bit), still same issue.

**Comment by hedenface** [comment]
Are your colleagues also using Chrome?

I'm at a bit of a loss to even think about how to debug this. The "Error: Could not read object configuration data!" string comes from the `object_data_error` function in `cgiutils.c` and is called in several cgi files after `read_all_object_configuration_data` returns `ERROR`. This literally means that it can't read the object config data. This wouldn't have anything to do with the browser you're using - unless there's some weird configuration going on in Apache.

What does your `nagios.log` file say after getting the error?

**Comment by wiardvanrij** [comment]
My colleagues are also using Chrome. 

I'm also very much lost on how to proceed on this. 

- nagios.log gives 0 output on the error
- apache log gives the same output as it would for my colleague. All http 200 requests.
- syslog no output

I literally have nothing to work on.

**Comment by hedenface** [comment]
I have a few questions:

Is this server a production server? Was it compiled from source or installed via some package manager?

Do you have any experience developing?

Can you set up a different Core server in addition to this one?

**Comment by wiardvanrij** [comment]
- It is compiled from source
- production server
- yes
- Could you elaborate?

**Comment by hedenface** [comment]
Just to see if it causes the same issue - set up an additional Core server, configure some checks, and see if you get the same problem?

Also, if I were you, I'd pick one of the problem cgis, and pepper it with `printf()` statements, or `syslog()` calls, or the regular nagios log function `logit()`, and then recompile. The workflow looks something like:

```
cd ~/Repos/nagioscore/cgis
<< edit and save status.c >>
make status.cgi
cp status.cgi /usr/local/nagios/bin/
```

**Comment by hedenface** [comment]
Whoops. Not bin/, but sbin/:
```
cd ~/Repos/nagioscore/cgis
<< edit and save status.c >>
make status.cgi
cp status.cgi /usr/local/nagios/sbin/
```

**Comment by hedenface** [comment]
What a weird thing. I was messing around and doing some compiling and installing, and I ran into an issue somewhat similar. Except that I wasn't getting anything on any browser.

It was fixed by re-issuing a `make install-cgis` command in the source dir after a make all.

**Comment by EquisTango** [comment]
I'm having the same issue (but inverted browsers). We all use Firefox, my colleagues are ok, I get an error. I had to install Chrome just to view the Nagios status. The funny part is I do this from 4 different PCs (3 Fedora, 1 Windows 10) and I only have this problem on 3 of them (1 Fedora works ok).

![firefox-chrome](https://user-images.githubusercontent.com/5860683/41193069-03e9fea8-6bde-11e8-90d3-5fab4a41bb5a.png)

Same request, different browsers, different status. I can see by the query_time that it's a fresh response every time.

- CentOS 7.
- nagios-4.3.4-5 (from EPEL).
- httpd-2.4.6-80.
- Kernel 4.17.0-1 (tried other kernels too).
- Tried SELinux disabled, permissive, enabled.
- Cleared Firefox cache, even started with a fresh Firefox profile.
- Checked all permisions for Nagios and Apache.
- Restarted services, rebooted the server.
- Reinstalled nagios from packages (yum reinstall nagios\*).
- Reinstalled all packages (yum reinstall \*).
- Nagios configtest -v is ok.
- Works with Curl.
- nagios.log gives 0 output on the error
- apache access.log gives the same output (200) for both requests. Nothing on error.log.
- Inspected headers for the request, even simulated same request headers on both browsers (I set all request headers on Firefox to be the same as Chrome and I still get a different response).
- This server is accessible from the Internet through an nginx reverse proxy with HTTPS, and the problem is still there.

Don't know where else to look or what else to try.

**Comment by wiardvanrij** [comment]
lol @EquisTango 
You know you remove the url in the address bar but it is still visable in the header?

Anyway, thanks for adding your input! Glad I'm not the only one lol

**Comment by EquisTango** [comment]
Haha @wiardvanrij , ok no biggie (I was in a hurry).

**Comment by EquisTango** [comment]
Ok. I finally made it work, but I don't know what did it.

I installed a completely new server and rsynced the configuration files and the problem persisted.

So I backed up all config files and removed everything unnecessary. I started with a very minimal config (one contact, one host, ping only). It worked.

So I started copying and pasting small chunks from the old config files and after each chunk I ran nagios config test, restarted nagios, and refreshed browser. It worked.

I ended up with basically all the original config back, but now it works. I really don't know what fixed it.

**Comment by hedenface** [comment]
Yes this is a weird issue. When I had experienced it, all I did to fix it was `make install-cgis`.

**Comment by drook** [comment]
Well, I stepped onto it right mow. In my case, this is also Centos, and I'm getting it in specific Firefox only. Unfortunately, I cannot *make install-cgis(, since this is rpm binary package installation, and I've already accomplished all the previous mentioned quest stages here - and this was fuile. So...

**Comment by ArDark2** [comment]
I have same problem with Chrome 70.0.3538.110. in FF and IE (latest) atm, all fine :/
nagios 4.4.2 compiled from tarball.
only summary.cgi works, all others (include *json.cgi is not)

**Comment by ibucur** [comment]
I have the same problem (it is working on almost all browsers but on chrome for android or windows 10 it does not - but works on firefox for android/windows).

I have checked logs and nothing, selinux is disabled, cgis are installed, fcgiwrap installed.

platform: debian 9
nagios core: compiled and installed from tatball. Version 4.4.3
web server: nginx 1.10.3

Chrome versions:
Mozilla/5.0 (Linux; Android 9; ONEPLUS A6003) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Mobile Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

Hope it helps. It's annoying to start using another browser

**Comment by daarro** [comment]
I just run into this as well.
Fresh Nagios installation on a Centos VM, installed from package (4.4.5-7.el7). Only a single host added to the configuration, besides localhost, and it happens. Nothing wrong shows up in the Apache/Nagios logs, configuration verified successfully.

I'm accessing GUI from MacOS. Safari and Chrome run into the issue, Curl is fine though, Firefox also o_O
My colleague connects to the same Nagios instance and doesn't experience any issues (neither in Chrome/Safari/Firefox).
This is insane!

**Comment by ptrrkssn** [comment]
Same issue here....

CentOS 6 (yes, I know, it should be upgraded soon)
Nagios Core 4.4.3
Apache httpd 2.2.15

Works for some users, using some browsers, and not for others...

**Comment by andreasruxanda** [comment]
Just in case anyone will face the same issue: we were able to pinpoint this problem as being related to the OS and/or browser language.
Switching the browser from Spanish to English fixed it.

**Comment by nscblauensteiner** [comment]
> Just in case anyone will face the same issue: we were able to pinpoint this problem as being related to the OS and/or browser language. Switching the browser from Spanish to English-US fixed it.

Worked for me, thank you very much!
